/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NetworksProjectPackage;

import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Drew Jeffrey
 */
//This class will draw and handle events for the main menu
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    ClientGUIController master = null;

    public mainMenu() {
        initComponents();
        putWindowInCenter();
    }

    public mainMenu(ClientGUIController controller) {
        initComponents();
        master = controller;
        putWindowInCenter();
    }

    public void putWindowInCenter() {
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

// Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

// Move the window
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        joinGame = new javax.swing.JButton();
        hostGame = new javax.swing.JButton();
        exitGame = new javax.swing.JButton();
        mmTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setForeground(new java.awt.Color(51, 102, 255));
        setResizable(false);

        joinGame.setBackground(new java.awt.Color(153, 153, 255));
        joinGame.setText("Join Game");
        joinGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinGameMouseClicked(evt);
            }
        });

        hostGame.setBackground(new java.awt.Color(153, 153, 255));
        hostGame.setText("Host Game");
        hostGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostGameMouseClicked(evt);
            }
        });

        exitGame.setBackground(new java.awt.Color(153, 153, 255));
        exitGame.setText("Exit Game");
        exitGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitGameMouseClicked(evt);
            }
        });

        mmTitle.setFont(new java.awt.Font("SimHei", 1, 48)); // NOI18N
        mmTitle.setForeground(new java.awt.Color(204, 0, 0));
        mmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmTitle.setText("Orbit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(joinGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(exitGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hostGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mmTitle, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mmTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joinGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hostGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitGame)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinGameMouseClicked
        // Code to allow user to join an existing game
    }//GEN-LAST:event_joinGameMouseClicked

    private void hostGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostGameMouseClicked
        // Code to allow user to become a new host and start a new game on his computer
        //Currently this just draws the game screen without any regard for networking
        master.drawGameScreen();
    }//GEN-LAST:event_hostGameMouseClicked

    private void exitGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitGameMouseClicked
        // Ends the program
        if (JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Leave?", "Leave Game?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitGameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitGame;
    private javax.swing.JButton hostGame;
    private javax.swing.JButton joinGame;
    private javax.swing.JLabel mmTitle;
    // End of variables declaration//GEN-END:variables
}
