/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NetworksProjectPackage;

import java.awt.Toolkit;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.util.*;
import java.net.*;

/**
 *
 * @author Drew Jeffrey
 */
//This class will draw and handle events for the main menu
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    ClientGUIController master = null;

    public mainMenu() {
        initComponents();
        putWindowInCenter();
    }

    public mainMenu(ClientGUIController controller) {
        initComponents();
        master = controller;
        putWindowInCenter();
        this.jTextField1.setVisible(false);
        this.jComboBoxJoinList.setVisible(false);
    }

    public void putWindowInCenter() {
        // Get the size of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

// Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width - w) / 2;
        int y = (dim.height - h) / 2;

// Move the window
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        joinGame = new javax.swing.JButton();
        hostGame = new javax.swing.JButton();
        exitGame = new javax.swing.JButton();
        mmTitle = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxJoinList = new javax.swing.JComboBox();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setForeground(new java.awt.Color(51, 102, 255));
        setResizable(false);

        joinGame.setBackground(new java.awt.Color(153, 153, 255));
        joinGame.setText("Join Game");
        joinGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                joinGameMouseClicked(evt);
            }
        });
        joinGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGameActionPerformed(evt);
            }
        });

        hostGame.setBackground(new java.awt.Color(153, 153, 255));
        hostGame.setText("Host Game");
        hostGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hostGameMouseClicked(evt);
            }
        });
        hostGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostGameActionPerformed(evt);
            }
        });

        exitGame.setBackground(new java.awt.Color(153, 153, 255));
        exitGame.setText("Exit Game");
        exitGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitGameMouseClicked(evt);
            }
        });

        mmTitle.setFont(new java.awt.Font("SimHei", 1, 48)); // NOI18N
        mmTitle.setForeground(new java.awt.Color(204, 0, 0));
        mmTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmTitle.setText("Orbit");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automatic Connection", "Manual Connection" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBoxJoinList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select active server" }));
        jComboBoxJoinList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJoinListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(mmTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joinGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(hostGame, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 177, Short.MAX_VALUE)
                    .addComponent(exitGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jComboBoxJoinList, javax.swing.GroupLayout.Alignment.TRAILING, 0, 177, Short.MAX_VALUE))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mmTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinGame)
                .addGap(4, 4, 4)
                .addComponent(jComboBoxJoinList, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hostGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void joinGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_joinGameMouseClicked
        // Code to allow user to join an existing game
        //ask networkcontroller to contact the sessionserver to get a list of hosting servers

       this.jComboBoxJoinList.removeAllItems();

       master.requestGameServers();


        this.jComboBoxJoinList.setVisible(true);

        //this.jComboBoxJoinList.add


    }//GEN-LAST:event_joinGameMouseClicked

    private void hostGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hostGameMouseClicked
        // Code to allow user to become a new host and start a new game on his computer
        //Currently this just draws the game screen without any regard for networking
        byte[] byteBuffer = new byte[2];
        byteBuffer[0] = (byte)((NetworkController.clientListenPortNumber) >> 8);
        byteBuffer[1] = (byte)(NetworkController.clientListenPortNumber);
        master.mainController.networkController.getUDPClient().sendPacket(NetworkController.sessionServerAddress, NetworkController.sessionServerListenPortNumber, byteBuffer, ProtocolInfo.TYPE_UNICAST_HOSTGAME);
        master.drawGameScreen();
        master.startNetworkController();
    }//GEN-LAST:event_hostGameMouseClicked

    private void exitGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitGameMouseClicked
        // Ends the program
        if (JOptionPane.showConfirmDialog(null, "Are You Sure You Want to Leave?", "Leave Game?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitGameMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(this.jComboBox1.getSelectedIndex() == 0)
        {
            this.jTextField1.setVisible(false);
        }else
        {
            this.jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void hostGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostGameActionPerformed

    private void jComboBoxJoinListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJoinListActionPerformed
        
                String text = (String)this.jComboBoxJoinList.getSelectedItem();
                System.out.println("about to enter loop");
                if(text == null)
                {
                    System.out.println("haha");
                }else
                {
                    System.out.println(text);
                }
                if( text != null && !text.equals("Select a server address"))
                {
                    try{
                        InetAddress ip = InetAddress.getByName(text.substring(1, text.length()));
                        NetworkController.serverAddress = ip;
                        System.out.println("Server address is updated to " + NetworkController.serverAddress.toString());
                        NetworkController.serverListenPortNumber = this.master.mainController.getActiveGameServers().get(ip);
                        System.out.println("Server port is "+ NetworkController.serverListenPortNumber);
                        master.drawGameScreen();
                        master.startNetworkController();
                    }catch(UnknownHostException e)
                    {
                        System.out.println(e);
                    }
                }
        
    }//GEN-LAST:event_jComboBoxJoinListActionPerformed

    private void joinGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinGameActionPerformed

    public void updateServerListComboBox(InetAddress ip){
        if(this.jComboBoxJoinList.getItemCount() == 0)
        {
            this.jComboBoxJoinList.addItem("Select a server address");
        }
        this.jComboBoxJoinList.addItem(ip.toString());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitGame;
    private javax.swing.JButton hostGame;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBoxJoinList;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton joinGame;
    private javax.swing.JLabel mmTitle;
    // End of variables declaration//GEN-END:variables
}
